#!/bin/bash --login
#$ -N TC-ELES
#$ -pe hpc.pe 256
#$ -cwd
#$ -P hpc-ar-m3cfd

module load apps/gcc/openfoam/v1812
source $foamDotFile

# cd ${0%/*} || exit 1                                    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

##################################################################################################

echo Creating Mesh...
runApplication blockMesh
runApplication checkMesh

echo "Restore 0/ from 0_orig/"
if [ -d 0_orig ]
then
    rm -rf 0
    cp -r 0_orig 0
else
    echo "    Warning: no 0_orig/ found"
fi

echo "Set decomposition"
foamDictionary -entry method -set ptscotch system/decomposeParDict
foamDictionary -entry numberOfSubdomains -set $NPROCS system/decomposeParDict

oldDecomp=$(echo processor* | wc -w)
if [[ "$oldDecomp" != "$NPROCS" ]]
then
  if [ "$oldDecomp" -gt 0 ]
  then
    echo "We need to redistribute the mesh for: $NPROCS"
    if [ "$oldDecomp" -gt "$NPROCS" ]; then
      echo "Old decomposition is greater than allocated resource"
      echo "This condition is not implemented"
    else
      runParallel -o redistributePar -overwrite -mergeTol 1e-9
    fi
  else
    echo "We need to decompose the mesh for: $NPROCS"
    runParallel decomposePar
  fi
fi

export RANSsolver=$(getApplication)

echo "Renumbering meshes"
runParallel renumberMesh -overwrite -constant
echo "Running potentialFoam"
runParallel potentialFoam
echo "Running Solver $RANSsolver with $NPROCS processes"
runParallel -a $RANSsolver

exit 0
